
EXCEPTION | 2022-09-16 08:07:09 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:07:15 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-16 08:07:38 | WD_ERROR: EXP => 12355 | REC => 12356 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:07:40 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:07:40 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 08:08:10 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:08:10 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:08:16 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-16 08:08:39 | WD_ERROR: EXP => 12598 | REC => 12599 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:08:41 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:08:41 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 08:09:12 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:09:12 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:09:16 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-16 08:09:39 | WD_ERROR: EXP => 12837 | REC => 12838 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:09:42 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:09:42 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 08:10:13 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:10:13 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:10:17 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-16 08:10:39 | WD_ERROR: EXP => 13076 | REC => 13077 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:10:43 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:10:43 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 08:11:14 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:11:14 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 08:11:15 | <<<--- | Erro ao obter hora de Servidor NTP: null[libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:551), libcore.io.IoBridge.recvfrom(IoBridge.java:509), java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:161), java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:169), java.net.DatagramSocket.receive(DatagramSocket.java:250), org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:89), br.inf.planeta.pedagio.DateTimeNTPServer.setSystemDateTimeWithDateTimeFromNTPServer(DateTimeNTPServer.java:25), br.inf.planeta.services.OneSecService$1.run(OneSecService.java:189), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422), java.util.concurrent.FutureTask.run(FutureTask.java:237), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | br.inf.planeta.services.OneSecService$1 (run line: 189) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (run line: 237)
ETH_LOG | 2022-09-16 08:11:17 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
REST | 2022-09-16 08:11:19 | --->>> | Response: {"VersaoSoftware":"9.6.5","Antenas":[{"VersaoSoftware":"0000012F","NomeLeitor":"SCR916","NumeroSerieLeitor":"5F500F53","NumLeitor":0,"BlStatusLeitor":1}],"ContadoresInternos":[0,0],"DataHora":"2022-09-16 08:11:19","NumeroSerieSLM":"8000B0CC","SLMTempoExecucao":3326,"AndroidTempoExecucao":3349} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-16 08:11:40 | WD_ERROR: EXP => 13319 | REC => 13320 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:11:44 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:11:44 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 08:12:15 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:12:15 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:12:18 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-16 08:12:40 | WD_ERROR: EXP => 13558 | REC => 13559 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:12:45 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:12:45 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 08:13:16 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:13:16 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:13:18 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-16 08:13:41 | WD_ERROR: EXP => 13801 | REC => 13802 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:13:46 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:13:46 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 08:14:17 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:14:17 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:14:19 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-16 08:14:41 | WD_ERROR: EXP => 14040 | REC => 14041 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:14:48 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:14:48 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 08:15:18 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:15:18 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:15:19 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
DAILY_STATS | 2022-09-16 08:15:33 | {} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

VLIB_SESSION_STATS | 2022-09-16 08:15:33 | {"vmeshVersionStr":"","vlibVersionStr":"1.2.0-global","vlibId":"","vlibGitVersion":"4749542076657273696F6E206E6F7420617661696C61626C652100000000000000000000000000000000","ulibVersionStr":"1.0.1","samCsn":"58434C0062E15DF9","samBuildTime":"23:10:19","samBuildDate":"Nov 12 2019","samAtr":"3B1D97434C5F53414D00143800009000","readerModel":"SCR916","enabledKernelApps":[0,6,6,6,0,0,0,0,0,0,0,0,0,0,0,0],"emvSamConfig":"3000010545434F39","unifiedControlRequest":0,"configControlRequest":0,"enabledKernelBits":67108878,"httpReuses":0,"lastPspData":0,"lastSlsData":1663323365,"listFlags":134217732,"onlineTimeout":-3565,"pspErrors":0,"pspServerHit":0,"pspServerStatus":0,"pspUrlIndex":0,"qrcodeTransactions":0,"readerErrors":0,"emvCancellations":0,"readerSn":1599082323,"readerVersion":303,"rfu":0,"dnsErrors":0,"diskWriteFail":0,"diskReadFail":0,"emvConfirmations":0,"samErrors":0,"samResets":1,"samTtc":0,"samVersion":14356,"sessionUnifiedAdded":0,"sessionUnifiedRemoved":0,"sessionUnifiedUpdated":0,"size":477,"slsServerHit":3567,"startTime":1663323367,"tcpConnections":1,"tcpErrors":0,"tcpRetries":0,"timestamp":1663326932,"tlsHandshakeErrors":0,"transactionSuccess":0,"bytesSent":184,"emvTransactions":0,"unifiedListItems":0,"unsyncedMismatchCount":0,"updateServerStatus":1,"virtualStatus":0,"virtualTransactions":0,"bytesReceived":69,"avrListItems":0,"vlibUptime":3565,"avrGlobalCount":0,"abtTransactions":0,"vreadyStatus":1} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-16 08:15:42 | WD_ERROR: EXP => 14283 | REC => 14284 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:15:49 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:15:49 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 08:16:16 | <<<--- | Erro ao obter hora de Servidor NTP: null[libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:551), libcore.io.IoBridge.recvfrom(IoBridge.java:509), java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:161), java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:169), java.net.DatagramSocket.receive(DatagramSocket.java:250), org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:89), br.inf.planeta.pedagio.DateTimeNTPServer.setSystemDateTimeWithDateTimeFromNTPServer(DateTimeNTPServer.java:25), br.inf.planeta.services.OneSecService$1.run(OneSecService.java:189), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422), java.util.concurrent.FutureTask.run(FutureTask.java:237), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | br.inf.planeta.services.OneSecService$1 (run line: 189) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (run line: 237)
EXCEPTION | 2022-09-16 08:16:19 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:16:19 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
REST | 2022-09-16 08:16:20 | --->>> | Response: {"VersaoSoftware":"9.6.5","Antenas":[{"VersaoSoftware":"0000012F","NomeLeitor":"SCR916","NumeroSerieLeitor":"5F500F53","NumLeitor":0,"BlStatusLeitor":1}],"ContadoresInternos":[0,0],"DataHora":"2022-09-16 08:16:20","NumeroSerieSLM":"8000B0CC","SLMTempoExecucao":3627,"AndroidTempoExecucao":3650} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

ETH_LOG | 2022-09-16 08:16:20 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-16 08:16:43 | WD_ERROR: EXP => 14526 | REC => 14527 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:16:50 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:16:50 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 08:17:20 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:17:20 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

ETH_LOG | 2022-09-16 08:17:21 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-16 08:17:44 | WD_ERROR: EXP => 14769 | REC => 14770 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:17:51 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:17:51 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:18:22 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

EXCEPTION | 2022-09-16 08:18:22 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 08:18:22 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:18:45 | WD_ERROR: EXP => 15012 | REC => 15013 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:18:53 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:18:53 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:19:23 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

EXCEPTION | 2022-09-16 08:19:23 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 08:19:23 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:19:45 | WD_ERROR: EXP => 15251 | REC => 15252 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:19:54 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:19:54 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:20:24 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

EXCEPTION | 2022-09-16 08:20:24 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:20:24 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:20:46 | WD_ERROR: EXP => 15494 | REC => 15495 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:20:55 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:20:55 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 08:21:17 | <<<--- | Erro ao obter hora de Servidor NTP: null[libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:551), libcore.io.IoBridge.recvfrom(IoBridge.java:509), java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:161), java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:169), java.net.DatagramSocket.receive(DatagramSocket.java:250), org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:89), br.inf.planeta.pedagio.DateTimeNTPServer.setSystemDateTimeWithDateTimeFromNTPServer(DateTimeNTPServer.java:25), br.inf.planeta.services.OneSecService$1.run(OneSecService.java:189), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422), java.util.concurrent.FutureTask.run(FutureTask.java:237), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | br.inf.planeta.services.OneSecService$1 (run line: 189) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (run line: 237)
REST | 2022-09-16 08:21:21 | --->>> | Response: {"VersaoSoftware":"9.6.5","Antenas":[{"VersaoSoftware":"0000012F","NomeLeitor":"SCR916","NumeroSerieLeitor":"5F500F53","NumLeitor":0,"BlStatusLeitor":1}],"ContadoresInternos":[0,0],"DataHora":"2022-09-16 08:21:21","NumeroSerieSLM":"8000B0CC","SLMTempoExecucao":3928,"AndroidTempoExecucao":3951} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
ETH_LOG | 2022-09-16 08:21:25 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

EXCEPTION | 2022-09-16 08:21:25 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:21:25 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:21:47 | WD_ERROR: EXP => 15737 | REC => 15738 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:21:56 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:21:56 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:22:26 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

EXCEPTION | 2022-09-16 08:22:26 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:22:26 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:22:48 | WD_ERROR: EXP => 15980 | REC => 15981 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:22:57 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:22:57 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:23:27 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

EXCEPTION | 2022-09-16 08:23:27 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:23:27 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:23:49 | WD_ERROR: EXP => 16223 | REC => 16224 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:23:58 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:23:58 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:24:28 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

EXCEPTION | 2022-09-16 08:24:28 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:24:28 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:24:50 | WD_ERROR: EXP => 16466 | REC => 16467 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:24:59 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:24:59 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:25:29 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

EXCEPTION | 2022-09-16 08:25:29 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:25:29 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
DAILY_STATS | 2022-09-16 08:25:33 | {} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

VLIB_SESSION_STATS | 2022-09-16 08:25:33 | {"vmeshVersionStr":"","vlibVersionStr":"1.2.0-global","vlibId":"","vlibGitVersion":"4749542076657273696F6E206E6F7420617661696C61626C652100000000000000000000000000000000","ulibVersionStr":"1.0.1","samCsn":"58434C0062E15DF9","samBuildTime":"23:10:19","samBuildDate":"Nov 12 2019","samAtr":"3B1D97434C5F53414D00143800009000","readerModel":"SCR916","enabledKernelApps":[0,6,6,6,0,0,0,0,0,0,0,0,0,0,0,0],"emvSamConfig":"3000010545434F39","unifiedControlRequest":0,"configControlRequest":0,"enabledKernelBits":67108878,"httpReuses":0,"lastPspData":0,"lastSlsData":1663323365,"listFlags":134217732,"onlineTimeout":-4165,"pspErrors":0,"pspServerHit":0,"pspServerStatus":0,"pspUrlIndex":0,"qrcodeTransactions":0,"readerErrors":0,"emvCancellations":0,"readerSn":1599082323,"readerVersion":303,"rfu":0,"dnsErrors":0,"diskWriteFail":0,"diskReadFail":0,"emvConfirmations":0,"samErrors":0,"samResets":1,"samTtc":0,"samVersion":14356,"sessionUnifiedAdded":0,"sessionUnifiedRemoved":0,"sessionUnifiedUpdated":0,"size":477,"slsServerHit":4167,"startTime":1663323367,"tcpConnections":1,"tcpErrors":0,"tcpRetries":0,"timestamp":1663327532,"tlsHandshakeErrors":0,"transactionSuccess":0,"bytesSent":184,"emvTransactions":0,"unifiedListItems":0,"unsyncedMismatchCount":0,"updateServerStatus":1,"virtualStatus":0,"virtualTransactions":0,"bytesReceived":69,"avrListItems":0,"vlibUptime":4165,"avrGlobalCount":0,"abtTransactions":0,"vreadyStatus":1} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-16 08:25:51 | WD_ERROR: EXP => 16709 | REC => 16710 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:26:00 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:26:00 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 08:26:17 | <<<--- | Erro ao obter hora de Servidor NTP: null[libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:551), libcore.io.IoBridge.recvfrom(IoBridge.java:509), java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:161), java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:169), java.net.DatagramSocket.receive(DatagramSocket.java:250), org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:89), br.inf.planeta.pedagio.DateTimeNTPServer.setSystemDateTimeWithDateTimeFromNTPServer(DateTimeNTPServer.java:25), br.inf.planeta.services.OneSecService$1.run(OneSecService.java:189), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422), java.util.concurrent.FutureTask.run(FutureTask.java:237), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | br.inf.planeta.services.OneSecService$1 (run line: 189) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (run line: 237)
REST | 2022-09-16 08:26:22 | --->>> | Response: {"VersaoSoftware":"9.6.5","Antenas":[{"VersaoSoftware":"0000012F","NomeLeitor":"SCR916","NumeroSerieLeitor":"5F500F53","NumLeitor":0,"BlStatusLeitor":1}],"ContadoresInternos":[0,0],"DataHora":"2022-09-16 08:26:22","NumeroSerieSLM":"8000B0CC","SLMTempoExecucao":4229,"AndroidTempoExecucao":4252} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
ETH_LOG | 2022-09-16 08:26:29 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

EXCEPTION | 2022-09-16 08:26:30 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:26:30 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:26:51 | WD_ERROR: EXP => 16948 | REC => 16949 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:27:01 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:27:01 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:27:30 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:27:32 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:27:32 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:27:51 | WD_ERROR: EXP => 17187 | REC => 17188 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:28:02 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:28:02 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:28:31 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:28:33 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:28:33 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:28:51 | WD_ERROR: EXP => 17426 | REC => 17427 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:29:04 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:29:04 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:29:32 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:29:34 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:29:34 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:29:52 | WD_ERROR: EXP => 17669 | REC => 17670 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:30:05 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:30:05 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:30:33 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:30:35 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:30:35 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:30:53 | WD_ERROR: EXP => 17912 | REC => 17913 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:31:06 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:31:06 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 08:31:18 | <<<--- | Erro ao obter hora de Servidor NTP: null[libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:551), libcore.io.IoBridge.recvfrom(IoBridge.java:509), java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:161), java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:169), java.net.DatagramSocket.receive(DatagramSocket.java:250), org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:89), br.inf.planeta.pedagio.DateTimeNTPServer.setSystemDateTimeWithDateTimeFromNTPServer(DateTimeNTPServer.java:25), br.inf.planeta.services.OneSecService$1.run(OneSecService.java:189), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422), java.util.concurrent.FutureTask.run(FutureTask.java:237), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | br.inf.planeta.services.OneSecService$1 (run line: 189) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (run line: 237)
REST | 2022-09-16 08:31:23 | --->>> | Response: {"VersaoSoftware":"9.6.5","Antenas":[{"VersaoSoftware":"0000012F","NomeLeitor":"SCR916","NumeroSerieLeitor":"5F500F53","NumLeitor":0,"BlStatusLeitor":1}],"ContadoresInternos":[0,0],"DataHora":"2022-09-16 08:31:23","NumeroSerieSLM":"8000B0CC","SLMTempoExecucao":4530,"AndroidTempoExecucao":4553} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
ETH_LOG | 2022-09-16 08:31:34 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:31:36 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:31:36 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:31:53 | WD_ERROR: EXP => 18151 | REC => 18152 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:32:07 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:32:07 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:32:35 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:32:38 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:32:38 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:32:54 | WD_ERROR: EXP => 18394 | REC => 18395 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:33:08 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:33:08 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:33:36 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:33:39 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:33:39 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:33:55 | WD_ERROR: EXP => 18637 | REC => 18638 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:34:10 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:34:10 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:34:37 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:34:41 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:34:41 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:34:56 | WD_ERROR: EXP => 18880 | REC => 18881 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:35:12 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:35:12 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
DAILY_STATS | 2022-09-16 08:35:34 | {} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

