VLIB_SESSION_STATS | 2022-09-16 08:35:34 | {"vmeshVersionStr":"","vlibVersionStr":"1.2.0-global","vlibId":"","vlibGitVersion":"4749542076657273696F6E206E6F7420617661696C61626C652100000000000000000000000000000000","ulibVersionStr":"1.0.1","samCsn":"58434C0062E15DF9","samBuildTime":"23:10:19","samBuildDate":"Nov 12 2019","samAtr":"3B1D97434C5F53414D00143800009000","readerModel":"SCR916","enabledKernelApps":[0,6,6,6,0,0,0,0,0,0,0,0,0,0,0,0],"emvSamConfig":"3000010545434F39","unifiedControlRequest":0,"configControlRequest":0,"enabledKernelBits":67108878,"httpReuses":0,"lastPspData":0,"lastSlsData":1663323365,"listFlags":134217732,"onlineTimeout":-4766,"pspErrors":0,"pspServerHit":0,"pspServerStatus":0,"pspUrlIndex":0,"qrcodeTransactions":0,"readerErrors":0,"emvCancellations":0,"readerSn":1599082323,"readerVersion":303,"rfu":0,"dnsErrors":0,"diskWriteFail":0,"diskReadFail":0,"emvConfirmations":0,"samErrors":0,"samResets":1,"samTtc":0,"samVersion":14356,"sessionUnifiedAdded":0,"sessionUnifiedRemoved":0,"sessionUnifiedUpdated":0,"size":477,"slsServerHit":4768,"startTime":1663323367,"tcpConnections":1,"tcpErrors":0,"tcpRetries":0,"timestamp":1663328133,"tlsHandshakeErrors":0,"transactionSuccess":0,"bytesSent":184,"emvTransactions":0,"unifiedListItems":0,"unsyncedMismatchCount":0,"updateServerStatus":1,"virtualStatus":0,"virtualTransactions":0,"bytesReceived":69,"avrListItems":0,"vlibUptime":4766,"avrGlobalCount":0,"abtTransactions":0,"vreadyStatus":1} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
ETH_LOG | 2022-09-16 08:35:38 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:35:43 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:35:43 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:35:56 | WD_ERROR: EXP => 19119 | REC => 19120 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:36:13 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:36:13 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 08:36:19 | <<<--- | Erro ao obter hora de Servidor NTP: null[libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:551), libcore.io.IoBridge.recvfrom(IoBridge.java:509), java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:161), java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:169), java.net.DatagramSocket.receive(DatagramSocket.java:250), org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:89), br.inf.planeta.pedagio.DateTimeNTPServer.setSystemDateTimeWithDateTimeFromNTPServer(DateTimeNTPServer.java:25), br.inf.planeta.services.OneSecService$1.run(OneSecService.java:189), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422), java.util.concurrent.FutureTask.run(FutureTask.java:237), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | br.inf.planeta.services.OneSecService$1 (run line: 189) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (run line: 237)
REST | 2022-09-16 08:36:24 | --->>> | Response: {"VersaoSoftware":"9.6.5","Antenas":[{"VersaoSoftware":"0000012F","NomeLeitor":"SCR916","NumeroSerieLeitor":"5F500F53","NumLeitor":0,"BlStatusLeitor":1}],"ContadoresInternos":[0,0],"DataHora":"2022-09-16 08:36:24","NumeroSerieSLM":"8000B0CC","SLMTempoExecucao":4831,"AndroidTempoExecucao":4854} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
ETH_LOG | 2022-09-16 08:36:39 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:36:43 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:36:43 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:36:57 | WD_ERROR: EXP => 19362 | REC => 19363 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:37:14 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:37:14 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:37:40 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:37:45 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:37:45 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:37:58 | WD_ERROR: EXP => 19605 | REC => 19606 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:38:16 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:38:16 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:38:41 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:38:46 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:38:46 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:38:59 | WD_ERROR: EXP => 19848 | REC => 19849 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:39:16 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:39:16 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:39:42 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:39:47 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:39:47 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:39:59 | WD_ERROR: EXP => 20087 | REC => 20088 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:40:17 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:40:17 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:40:43 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:40:48 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:40:48 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:40:59 | WD_ERROR: EXP => 20326 | REC => 20327 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:41:18 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:41:18 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 08:41:19 | <<<--- | Erro ao obter hora de Servidor NTP: null[libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:551), libcore.io.IoBridge.recvfrom(IoBridge.java:509), java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:161), java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:169), java.net.DatagramSocket.receive(DatagramSocket.java:250), org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:89), br.inf.planeta.pedagio.DateTimeNTPServer.setSystemDateTimeWithDateTimeFromNTPServer(DateTimeNTPServer.java:25), br.inf.planeta.services.OneSecService$1.run(OneSecService.java:189), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422), java.util.concurrent.FutureTask.run(FutureTask.java:237), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | br.inf.planeta.services.OneSecService$1 (run line: 189) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (run line: 237)
REST | 2022-09-16 08:41:25 | --->>> | Response: {"VersaoSoftware":"9.6.5","Antenas":[{"VersaoSoftware":"0000012F","NomeLeitor":"SCR916","NumeroSerieLeitor":"5F500F53","NumLeitor":0,"BlStatusLeitor":1}],"ContadoresInternos":[0,0],"DataHora":"2022-09-16 08:41:25","NumeroSerieSLM":"8000B0CC","SLMTempoExecucao":5132,"AndroidTempoExecucao":5155} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
ETH_LOG | 2022-09-16 08:41:44 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:41:49 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:41:49 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:42:00 | WD_ERROR: EXP => 20569 | REC => 20570 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:42:19 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:42:19 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:42:45 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:42:50 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:42:50 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:43:01 | WD_ERROR: EXP => 20812 | REC => 20813 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:43:20 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:43:20 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:43:46 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:43:51 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:43:51 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:44:02 | WD_ERROR: EXP => 21055 | REC => 21056 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:44:22 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:44:22 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:44:47 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:44:52 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:44:52 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:45:02 | WD_ERROR: EXP => 21294 | REC => 21295 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:45:22 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:45:22 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
DAILY_STATS | 2022-09-16 08:45:35 | {} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

VLIB_SESSION_STATS | 2022-09-16 08:45:35 | {"vmeshVersionStr":"","vlibVersionStr":"1.2.0-global","vlibId":"","vlibGitVersion":"4749542076657273696F6E206E6F7420617661696C61626C652100000000000000000000000000000000","ulibVersionStr":"1.0.1","samCsn":"58434C0062E15DF9","samBuildTime":"23:10:19","samBuildDate":"Nov 12 2019","samAtr":"3B1D97434C5F53414D00143800009000","readerModel":"SCR916","enabledKernelApps":[0,6,6,6,0,0,0,0,0,0,0,0,0,0,0,0],"emvSamConfig":"3000010545434F39","unifiedControlRequest":0,"configControlRequest":0,"enabledKernelBits":67108878,"httpReuses":0,"lastPspData":0,"lastSlsData":1663323365,"listFlags":134217732,"onlineTimeout":-5367,"pspErrors":0,"pspServerHit":0,"pspServerStatus":0,"pspUrlIndex":0,"qrcodeTransactions":0,"readerErrors":0,"emvCancellations":0,"readerSn":1599082323,"readerVersion":303,"rfu":0,"dnsErrors":0,"diskWriteFail":0,"diskReadFail":0,"emvConfirmations":0,"samErrors":0,"samResets":1,"samTtc":0,"samVersion":14356,"sessionUnifiedAdded":0,"sessionUnifiedRemoved":0,"sessionUnifiedUpdated":0,"size":477,"slsServerHit":5369,"startTime":1663323367,"tcpConnections":1,"tcpErrors":0,"tcpRetries":0,"timestamp":1663328734,"tlsHandshakeErrors":0,"transactionSuccess":0,"bytesSent":184,"emvTransactions":0,"unifiedListItems":0,"unsyncedMismatchCount":0,"updateServerStatus":1,"virtualStatus":0,"virtualTransactions":0,"bytesReceived":69,"avrListItems":0,"vlibUptime":5367,"avrGlobalCount":0,"abtTransactions":0,"vreadyStatus":1} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
ETH_LOG | 2022-09-16 08:45:48 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:45:53 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:45:53 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:46:03 | WD_ERROR: EXP => 21537 | REC => 21538 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:46:20 | <<<--- | Erro ao obter hora de Servidor NTP: null[libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:551), libcore.io.IoBridge.recvfrom(IoBridge.java:509), java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:161), java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:169), java.net.DatagramSocket.receive(DatagramSocket.java:250), org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:89), br.inf.planeta.pedagio.DateTimeNTPServer.setSystemDateTimeWithDateTimeFromNTPServer(DateTimeNTPServer.java:25), br.inf.planeta.services.OneSecService$1.run(OneSecService.java:189), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422), java.util.concurrent.FutureTask.run(FutureTask.java:237), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | br.inf.planeta.services.OneSecService$1 (run line: 189) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (run line: 237)
EXCEPTION | 2022-09-16 08:46:24 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:46:24 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
REST | 2022-09-16 08:46:26 | --->>> | Response: {"VersaoSoftware":"9.6.5","Antenas":[{"VersaoSoftware":"0000012F","NomeLeitor":"SCR916","NumeroSerieLeitor":"5F500F53","NumLeitor":0,"BlStatusLeitor":1}],"ContadoresInternos":[0,0],"DataHora":"2022-09-16 08:46:26","NumeroSerieSLM":"8000B0CC","SLMTempoExecucao":5433,"AndroidTempoExecucao":5456} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
ETH_LOG | 2022-09-16 08:46:49 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:46:54 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:46:54 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:47:04 | WD_ERROR: EXP => 21780 | REC => 21781 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:47:25 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:47:25 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:47:50 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:47:55 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:47:55 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:48:05 | WD_ERROR: EXP => 22023 | REC => 22024 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:48:26 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 08:48:26 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:48:51 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:48:56 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:48:56 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:49:06 | WD_ERROR: EXP => 22266 | REC => 22267 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:49:27 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:49:27 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:49:52 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:49:58 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:49:58 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:50:07 | WD_ERROR: EXP => 22509 | REC => 22510 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:50:28 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:50:28 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:50:53 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:50:59 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:50:59 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:51:07 | WD_ERROR: EXP => 22748 | REC => 22749 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:51:20 | <<<--- | Erro ao obter hora de Servidor NTP: null[libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:551), libcore.io.IoBridge.recvfrom(IoBridge.java:509), java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:161), java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:169), java.net.DatagramSocket.receive(DatagramSocket.java:250), org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:89), br.inf.planeta.pedagio.DateTimeNTPServer.setSystemDateTimeWithDateTimeFromNTPServer(DateTimeNTPServer.java:25), br.inf.planeta.services.OneSecService$1.run(OneSecService.java:189), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422), java.util.concurrent.FutureTask.run(FutureTask.java:237), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | br.inf.planeta.services.OneSecService$1 (run line: 189) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (run line: 237)
REST | 2022-09-16 08:51:27 | --->>> | Response: {"VersaoSoftware":"9.6.5","Antenas":[{"VersaoSoftware":"0000012F","NomeLeitor":"SCR916","NumeroSerieLeitor":"5F500F53","NumLeitor":0,"BlStatusLeitor":1}],"ContadoresInternos":[0,0],"DataHora":"2022-09-16 08:51:27","NumeroSerieSLM":"8000B0CC","SLMTempoExecucao":5734,"AndroidTempoExecucao":5757} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:51:30 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:51:30 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:51:54 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:52:00 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:52:00 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:52:08 | WD_ERROR: EXP => 22991 | REC => 22992 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:52:30 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:52:30 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:52:55 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:53:00 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:53:00 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:53:09 | WD_ERROR: EXP => 23234 | REC => 23235 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:53:31 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:53:31 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:53:56 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:54:02 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:54:02 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:54:09 | WD_ERROR: EXP => 23473 | REC => 23474 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:54:32 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:54:32 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:54:57 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:55:02 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:55:02 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:55:10 | WD_ERROR: EXP => 23716 | REC => 23717 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:55:33 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:55:33 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
DAILY_STATS | 2022-09-16 08:55:35 | {} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

VLIB_SESSION_STATS | 2022-09-16 08:55:35 | {"vmeshVersionStr":"","vlibVersionStr":"1.2.0-global","vlibId":"","vlibGitVersion":"4749542076657273696F6E206E6F7420617661696C61626C652100000000000000000000000000000000","ulibVersionStr":"1.0.1","samCsn":"58434C0062E15DF9","samBuildTime":"23:10:19","samBuildDate":"Nov 12 2019","samAtr":"3B1D97434C5F53414D00143800009000","readerModel":"SCR916","enabledKernelApps":[0,6,6,6,0,0,0,0,0,0,0,0,0,0,0,0],"emvSamConfig":"3000010545434F39","unifiedControlRequest":0,"configControlRequest":0,"enabledKernelBits":67108878,"httpReuses":0,"lastPspData":0,"lastSlsData":1663323365,"listFlags":134217732,"onlineTimeout":-5967,"pspErrors":0,"pspServerHit":0,"pspServerStatus":0,"pspUrlIndex":0,"qrcodeTransactions":0,"readerErrors":0,"emvCancellations":0,"readerSn":1599082323,"readerVersion":303,"rfu":0,"dnsErrors":0,"diskWriteFail":0,"diskReadFail":0,"emvConfirmations":0,"samErrors":0,"samResets":1,"samTtc":0,"samVersion":14356,"sessionUnifiedAdded":0,"sessionUnifiedRemoved":0,"sessionUnifiedUpdated":0,"size":477,"slsServerHit":5969,"startTime":1663323367,"tcpConnections":1,"tcpErrors":0,"tcpRetries":0,"timestamp":1663329334,"tlsHandshakeErrors":0,"transactionSuccess":0,"bytesSent":184,"emvTransactions":0,"unifiedListItems":0,"unsyncedMismatchCount":0,"updateServerStatus":1,"virtualStatus":0,"virtualTransactions":0,"bytesReceived":69,"avrListItems":0,"vlibUptime":5967,"avrGlobalCount":0,"abtTransactions":0,"vreadyStatus":1} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
ETH_LOG | 2022-09-16 08:55:58 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:56:03 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:56:03 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:56:10 | WD_ERROR: EXP => 23955 | REC => 23956 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:56:20 | <<<--- | Erro ao obter hora de Servidor NTP: null[libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:551), libcore.io.IoBridge.recvfrom(IoBridge.java:509), java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:161), java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:169), java.net.DatagramSocket.receive(DatagramSocket.java:250), org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:89), br.inf.planeta.pedagio.DateTimeNTPServer.setSystemDateTimeWithDateTimeFromNTPServer(DateTimeNTPServer.java:25), br.inf.planeta.services.OneSecService$1.run(OneSecService.java:189), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422), java.util.concurrent.FutureTask.run(FutureTask.java:237), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | br.inf.planeta.services.OneSecService$1 (run line: 189) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (run line: 237)
REST | 2022-09-16 08:56:28 | --->>> | Response: {"VersaoSoftware":"9.6.5","Antenas":[{"VersaoSoftware":"0000012F","NomeLeitor":"SCR916","NumeroSerieLeitor":"5F500F53","NumLeitor":0,"BlStatusLeitor":1}],"ContadoresInternos":[0,0],"DataHora":"2022-09-16 08:56:28","NumeroSerieSLM":"8000B0CC","SLMTempoExecucao":6035,"AndroidTempoExecucao":6058} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:56:33 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:56:33 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:56:59 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:57:03 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:57:03 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:57:10 | WD_ERROR: EXP => 24194 | REC => 24195 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:57:33 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:57:33 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:57:59 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:58:04 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:58:04 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:58:11 | WD_ERROR: EXP => 24437 | REC => 24438 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:58:34 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:58:34 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 08:59:00 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:59:05 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:59:05 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 08:59:12 | WD_ERROR: EXP => 24680 | REC => 24681 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 08:59:36 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 08:59:36 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 09:00:00 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 09:00:07 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 09:00:07 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 09:00:12 | WD_ERROR: EXP => 24919 | REC => 24920 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 09:00:37 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 09:00:37 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 09:01:01 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 09:01:08 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 09:01:08 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 09:01:13 | WD_ERROR: EXP => 25162 | REC => 25163 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 09:01:21 | <<<--- | Erro ao obter hora de Servidor NTP: null[libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:551), libcore.io.IoBridge.recvfrom(IoBridge.java:509), java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:161), java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:169), java.net.DatagramSocket.receive(DatagramSocket.java:250), org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:89), br.inf.planeta.pedagio.DateTimeNTPServer.setSystemDateTimeWithDateTimeFromNTPServer(DateTimeNTPServer.java:25), br.inf.planeta.services.OneSecService$1.run(OneSecService.java:189), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422), java.util.concurrent.FutureTask.run(FutureTask.java:237), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | br.inf.planeta.services.OneSecService$1 (run line: 189) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (run line: 237)
REST | 2022-09-16 09:01:29 | --->>> | Response: {"VersaoSoftware":"9.6.5","Antenas":[{"VersaoSoftware":"0000012F","NomeLeitor":"SCR916","NumeroSerieLeitor":"5F500F53","NumLeitor":0,"BlStatusLeitor":1}],"ContadoresInternos":[0,0],"DataHora":"2022-09-16 09:01:29","NumeroSerieSLM":"8000B0CC","SLMTempoExecucao":6336,"AndroidTempoExecucao":6359} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 09:01:39 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 09:01:39 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 09:02:02 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 09:02:10 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 09:02:10 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 09:02:13 | WD_ERROR: EXP => 25401 | REC => 25402 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 09:02:41 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 09:02:41 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 09:03:03 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 09:03:11 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 09:03:11 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 09:03:14 | WD_ERROR: EXP => 25644 | REC => 25645 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 09:03:42 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 09:03:42 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 09:04:04 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 09:04:13 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 09:04:13 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 09:04:15 | WD_ERROR: EXP => 25887 | REC => 25888 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 09:04:44 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 09:04:44 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
