
EXCEPTION | 2022-09-15 23:04:07 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-15 23:04:17 | WD_ERROR: EXP => 5812 | REC => 5813 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:04:38 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:04:38 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 23:04:52 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:05:08 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:05:08 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 23:05:11 | <<<--- | Erro ao obter hora de Servidor NTP: null[libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:551), libcore.io.IoBridge.recvfrom(IoBridge.java:509), java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:161), java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:169), java.net.DatagramSocket.receive(DatagramSocket.java:250), org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:89), br.inf.planeta.pedagio.DateTimeNTPServer.setSystemDateTimeWithDateTimeFromNTPServer(DateTimeNTPServer.java:25), br.inf.planeta.services.OneSecService$1.run(OneSecService.java:189), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422), java.util.concurrent.FutureTask.run(FutureTask.java:237), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | br.inf.planeta.services.OneSecService$1 (run line: 189) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (run line: 237)
REST | 2022-09-15 23:05:14 | --->>> | Response: {"VersaoSoftware":"9.6.5","Antenas":[{"VersaoSoftware":"0000012F","NomeLeitor":"SCR916","NumeroSerieLeitor":"5F500F53","NumLeitor":0,"BlStatusLeitor":1}],"ContadoresInternos":[0,0],"DataHora":"2022-09-15 23:05:14","NumeroSerieSLM":"8000B0CC","SLMTempoExecucao":1521,"AndroidTempoExecucao":1544} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-15 23:05:17 | WD_ERROR: EXP => 6051 | REC => 6052 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:05:39 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:05:39 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 23:05:53 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:06:09 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:06:09 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-15 23:06:18 | WD_ERROR: EXP => 6294 | REC => 6295 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:06:40 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:06:40 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 23:06:54 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:07:11 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:07:11 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-15 23:07:18 | WD_ERROR: EXP => 6533 | REC => 6534 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:07:42 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 23:07:42 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 23:07:55 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:08:13 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:08:13 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-15 23:08:18 | WD_ERROR: EXP => 6772 | REC => 6773 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:08:44 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:08:44 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 23:08:56 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:09:15 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:09:15 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-15 23:09:19 | WD_ERROR: EXP => 7015 | REC => 7016 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
DAILY_STATS | 2022-09-15 23:09:30 | {} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

VLIB_SESSION_STATS | 2022-09-15 23:09:30 | {"vmeshVersionStr":"","vlibVersionStr":"1.2.0-global","vlibId":"","vlibGitVersion":"4749542076657273696F6E206E6F7420617661696C61626C652100000000000000000000000000000000","ulibVersionStr":"1.0.1","samCsn":"58434C0062E15DF9","samBuildTime":"23:10:19","samBuildDate":"Nov 12 2019","samAtr":"3B1D97434C5F53414D00143800009000","readerModel":"SCR916","enabledKernelApps":[0,6,6,6,0,0,0,0,0,0,0,0,0,0,0,0],"emvSamConfig":"3000010545434F39","unifiedControlRequest":0,"configControlRequest":0,"enabledKernelBits":67108878,"httpReuses":0,"lastPspData":0,"lastSlsData":1663292404,"listFlags":134217732,"onlineTimeout":-1762,"pspErrors":0,"pspServerHit":0,"pspServerStatus":0,"pspUrlIndex":0,"qrcodeTransactions":0,"readerErrors":0,"emvCancellations":0,"readerSn":1599082323,"readerVersion":303,"rfu":0,"dnsErrors":0,"diskWriteFail":0,"diskReadFail":0,"emvConfirmations":0,"samErrors":0,"samResets":1,"samTtc":0,"samVersion":14356,"sessionUnifiedAdded":0,"sessionUnifiedRemoved":0,"sessionUnifiedUpdated":0,"size":477,"slsServerHit":1765,"startTime":1663292407,"tcpConnections":1,"tcpErrors":0,"tcpRetries":0,"timestamp":1663294169,"tlsHandshakeErrors":0,"transactionSuccess":0,"bytesSent":184,"emvTransactions":0,"unifiedListItems":0,"unsyncedMismatchCount":0,"updateServerStatus":1,"virtualStatus":0,"virtualTransactions":0,"bytesReceived":69,"avrListItems":0,"vlibUptime":1762,"avrGlobalCount":0,"abtTransactions":0,"vreadyStatus":1} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:09:46 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:09:46 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 23:09:57 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:10:12 | <<<--- | Erro ao obter hora de Servidor NTP: null[libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:551), libcore.io.IoBridge.recvfrom(IoBridge.java:509), java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:161), java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:169), java.net.DatagramSocket.receive(DatagramSocket.java:250), org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:89), br.inf.planeta.pedagio.DateTimeNTPServer.setSystemDateTimeWithDateTimeFromNTPServer(DateTimeNTPServer.java:25), br.inf.planeta.services.OneSecService$1.run(OneSecService.java:189), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422), java.util.concurrent.FutureTask.run(FutureTask.java:237), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | br.inf.planeta.services.OneSecService$1 (run line: 189) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (run line: 237)
REST | 2022-09-15 23:10:15 | --->>> | Response: {"VersaoSoftware":"9.6.5","Antenas":[{"VersaoSoftware":"0000012F","NomeLeitor":"SCR916","NumeroSerieLeitor":"5F500F53","NumLeitor":0,"BlStatusLeitor":1}],"ContadoresInternos":[0,0],"DataHora":"2022-09-15 23:10:15","NumeroSerieSLM":"8000B0CC","SLMTempoExecucao":1822,"AndroidTempoExecucao":1845} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:10:17 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 23:10:17 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-15 23:10:20 | WD_ERROR: EXP => 7258 | REC => 7259 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:10:47 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:10:47 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 23:10:58 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:11:18 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:11:18 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-15 23:11:20 | WD_ERROR: EXP => 7497 | REC => 7498 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:11:49 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:11:49 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 23:11:59 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:12:20 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 23:12:20 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-15 23:12:21 | WD_ERROR: EXP => 7739 | REC => 7740 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:12:51 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 23:12:51 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 23:13:00 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:13:21 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:13:21 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-15 23:13:22 | WD_ERROR: EXP => 7982 | REC => 7983 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:13:52 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:13:52 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 23:14:01 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:14:22 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:14:22 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

WD_ERROR | 2022-09-15 23:14:22 | WD_ERROR: EXP => 8221 | REC => 8222 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:14:53 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:14:53 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 23:15:02 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:15:13 | <<<--- | Erro ao obter hora de Servidor NTP: null[libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:551), libcore.io.IoBridge.recvfrom(IoBridge.java:509), java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:161), java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:169), java.net.DatagramSocket.receive(DatagramSocket.java:250), org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:89), br.inf.planeta.pedagio.DateTimeNTPServer.setSystemDateTimeWithDateTimeFromNTPServer(DateTimeNTPServer.java:25), br.inf.planeta.services.OneSecService$1.run(OneSecService.java:189), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422), java.util.concurrent.FutureTask.run(FutureTask.java:237), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | br.inf.planeta.services.OneSecService$1 (run line: 189) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (run line: 237)
REST | 2022-09-15 23:15:16 | --->>> | Response: {"VersaoSoftware":"9.6.5","Antenas":[{"VersaoSoftware":"0000012F","NomeLeitor":"SCR916","NumeroSerieLeitor":"5F500F53","NumLeitor":0,"BlStatusLeitor":1}],"ContadoresInternos":[0,0],"DataHora":"2022-09-15 23:15:16","NumeroSerieSLM":"8000B0CC","SLMTempoExecucao":2123,"AndroidTempoExecucao":2146} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:15:23 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:15:23 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

WD_ERROR | 2022-09-15 23:15:23 | WD_ERROR: EXP => 8464 | REC => 8465 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:15:54 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:15:54 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 23:16:03 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:16:24 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:16:24 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

WD_ERROR | 2022-09-15 23:16:24 | WD_ERROR: EXP => 8707 | REC => 8708 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:16:55 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:16:55 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 23:17:04 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:17:25 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:17:25 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

WD_ERROR | 2022-09-15 23:17:25 | WD_ERROR: EXP => 8950 | REC => 8951 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:17:56 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:17:56 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 23:18:05 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-15 23:18:25 | WD_ERROR: EXP => 9189 | REC => 9190 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:18:27 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 23:18:27 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 23:18:58 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:18:58 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 23:19:06 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-15 23:19:25 | WD_ERROR: EXP => 9428 | REC => 9429 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:19:28 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:19:28 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
DAILY_STATS | 2022-09-15 23:19:30 | {} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

VLIB_SESSION_STATS | 2022-09-15 23:19:30 | {"vmeshVersionStr":"","vlibVersionStr":"1.2.0-global","vlibId":"","vlibGitVersion":"4749542076657273696F6E206E6F7420617661696C61626C652100000000000000000000000000000000","ulibVersionStr":"1.0.1","samCsn":"58434C0062E15DF9","samBuildTime":"23:10:19","samBuildDate":"Nov 12 2019","samAtr":"3B1D97434C5F53414D00143800009000","readerModel":"SCR916","enabledKernelApps":[0,6,6,6,0,0,0,0,0,0,0,0,0,0,0,0],"emvSamConfig":"3000010545434F39","unifiedControlRequest":0,"configControlRequest":0,"enabledKernelBits":67108878,"httpReuses":0,"lastPspData":0,"lastSlsData":1663292404,"listFlags":134217732,"onlineTimeout":-2363,"pspErrors":0,"pspServerHit":0,"pspServerStatus":0,"pspUrlIndex":0,"qrcodeTransactions":0,"readerErrors":0,"emvCancellations":0,"readerSn":1599082323,"readerVersion":303,"rfu":0,"dnsErrors":0,"diskWriteFail":0,"diskReadFail":0,"emvConfirmations":0,"samErrors":0,"samResets":1,"samTtc":0,"samVersion":14356,"sessionUnifiedAdded":0,"sessionUnifiedRemoved":0,"sessionUnifiedUpdated":0,"size":477,"slsServerHit":2366,"startTime":1663292407,"tcpConnections":1,"tcpErrors":0,"tcpRetries":0,"timestamp":1663294770,"tlsHandshakeErrors":0,"transactionSuccess":0,"bytesSent":184,"emvTransactions":0,"unifiedListItems":0,"unsyncedMismatchCount":0,"updateServerStatus":1,"virtualStatus":0,"virtualTransactions":0,"bytesReceived":69,"avrListItems":0,"vlibUptime":2363,"avrGlobalCount":0,"abtTransactions":0,"vreadyStatus":1} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:19:59 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:19:59 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 23:20:07 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:20:13 | <<<--- | Erro ao obter hora de Servidor NTP: null[libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:551), libcore.io.IoBridge.recvfrom(IoBridge.java:509), java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:161), java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:169), java.net.DatagramSocket.receive(DatagramSocket.java:250), org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:89), br.inf.planeta.pedagio.DateTimeNTPServer.setSystemDateTimeWithDateTimeFromNTPServer(DateTimeNTPServer.java:25), br.inf.planeta.services.OneSecService$1.run(OneSecService.java:189), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422), java.util.concurrent.FutureTask.run(FutureTask.java:237), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | br.inf.planeta.services.OneSecService$1 (run line: 189) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (run line: 237)
REST | 2022-09-15 23:20:17 | --->>> | Response: {"VersaoSoftware":"9.6.5","Antenas":[{"VersaoSoftware":"0000012F","NomeLeitor":"SCR916","NumeroSerieLeitor":"5F500F53","NumLeitor":0,"BlStatusLeitor":1}],"ContadoresInternos":[0,0],"DataHora":"2022-09-15 23:20:17","NumeroSerieSLM":"8000B0CC","SLMTempoExecucao":2424,"AndroidTempoExecucao":2447} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-15 23:20:26 | WD_ERROR: EXP => 9671 | REC => 9672 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:20:30 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:20:30 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 23:21:00 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:21:00 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 23:21:08 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-15 23:21:27 | WD_ERROR: EXP => 9914 | REC => 9915 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:21:30 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:21:30 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 23:22:01 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:22:01 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 23:22:09 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-15 23:22:28 | WD_ERROR: EXP => 10157 | REC => 10158 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:22:31 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:22:31 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 23:23:02 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 23:23:02 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 23:23:10 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-15 23:23:28 | WD_ERROR: EXP => 10396 | REC => 10397 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:23:33 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 23:23:33 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 23:24:04 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 23:24:04 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 23:24:11 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-15 23:24:29 | WD_ERROR: EXP => 10639 | REC => 10640 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:24:35 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:24:35 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 23:25:06 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:25:06 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 23:25:12 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:25:14 | <<<--- | Erro ao obter hora de Servidor NTP: null[libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:551), libcore.io.IoBridge.recvfrom(IoBridge.java:509), java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:161), java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:169), java.net.DatagramSocket.receive(DatagramSocket.java:250), org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:89), br.inf.planeta.pedagio.DateTimeNTPServer.setSystemDateTimeWithDateTimeFromNTPServer(DateTimeNTPServer.java:25), br.inf.planeta.services.OneSecService$1.run(OneSecService.java:189), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422), java.util.concurrent.FutureTask.run(FutureTask.java:237), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | br.inf.planeta.services.OneSecService$1 (run line: 189) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (run line: 237)
REST | 2022-09-15 23:25:18 | --->>> | Response: {"VersaoSoftware":"9.6.5","Antenas":[{"VersaoSoftware":"0000012F","NomeLeitor":"SCR916","NumeroSerieLeitor":"5F500F53","NumLeitor":0,"BlStatusLeitor":1}],"ContadoresInternos":[0,0],"DataHora":"2022-09-15 23:25:18","NumeroSerieSLM":"8000B0CC","SLMTempoExecucao":2725,"AndroidTempoExecucao":2748} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-15 23:25:29 | WD_ERROR: EXP => 10878 | REC => 10879 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:25:36 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 23:25:36 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 23:26:06 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 23:26:06 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 23:26:13 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-15 23:26:30 | WD_ERROR: EXP => 11121 | REC => 11122 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:26:37 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:26:37 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 23:27:07 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:27:07 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 23:27:14 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-15 23:27:31 | WD_ERROR: EXP => 11364 | REC => 11365 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:27:37 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:27:37 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 23:28:08 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:28:08 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 23:28:15 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-15 23:28:32 | WD_ERROR: EXP => 11607 | REC => 11608 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:28:39 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:28:39 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 23:29:10 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:29:10 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 23:29:16 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
DAILY_STATS | 2022-09-15 23:29:31 | {} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

VLIB_SESSION_STATS | 2022-09-15 23:29:31 | {"vmeshVersionStr":"","vlibVersionStr":"1.2.0-global","vlibId":"","vlibGitVersion":"4749542076657273696F6E206E6F7420617661696C61626C652100000000000000000000000000000000","ulibVersionStr":"1.0.1","samCsn":"58434C0062E15DF9","samBuildTime":"23:10:19","samBuildDate":"Nov 12 2019","samAtr":"3B1D97434C5F53414D00143800009000","readerModel":"SCR916","enabledKernelApps":[0,6,6,6,0,0,0,0,0,0,0,0,0,0,0,0],"emvSamConfig":"3000010545434F39","unifiedControlRequest":0,"configControlRequest":0,"enabledKernelBits":67108878,"httpReuses":0,"lastPspData":0,"lastSlsData":1663292404,"listFlags":134217732,"onlineTimeout":-2964,"pspErrors":0,"pspServerHit":0,"pspServerStatus":0,"pspUrlIndex":0,"qrcodeTransactions":0,"readerErrors":0,"emvCancellations":0,"readerSn":1599082323,"readerVersion":303,"rfu":0,"dnsErrors":0,"diskWriteFail":0,"diskReadFail":0,"emvConfirmations":0,"samErrors":0,"samResets":1,"samTtc":0,"samVersion":14356,"sessionUnifiedAdded":0,"sessionUnifiedRemoved":0,"sessionUnifiedUpdated":0,"size":477,"slsServerHit":2967,"startTime":1663292407,"tcpConnections":1,"tcpErrors":0,"tcpRetries":0,"timestamp":1663295371,"tlsHandshakeErrors":0,"transactionSuccess":0,"bytesSent":184,"emvTransactions":0,"unifiedListItems":0,"unsyncedMismatchCount":0,"updateServerStatus":1,"virtualStatus":0,"virtualTransactions":0,"bytesReceived":69,"avrListItems":0,"vlibUptime":2964,"avrGlobalCount":0,"abtTransactions":0,"vreadyStatus":1} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-15 23:29:33 | WD_ERROR: EXP => 11850 | REC => 11851 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:29:41 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:29:41 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 23:30:11 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:30:11 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 23:30:15 | <<<--- | Erro ao obter hora de Servidor NTP: null[libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:551), libcore.io.IoBridge.recvfrom(IoBridge.java:509), java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:161), java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:169), java.net.DatagramSocket.receive(DatagramSocket.java:250), org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:89), br.inf.planeta.pedagio.DateTimeNTPServer.setSystemDateTimeWithDateTimeFromNTPServer(DateTimeNTPServer.java:25), br.inf.planeta.services.OneSecService$1.run(OneSecService.java:189), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422), java.util.concurrent.FutureTask.run(FutureTask.java:237), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | br.inf.planeta.services.OneSecService$1 (run line: 189) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (run line: 237)
ETH_LOG | 2022-09-15 23:30:17 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
REST | 2022-09-15 23:30:19 | --->>> | Response: {"VersaoSoftware":"9.6.5","Antenas":[{"VersaoSoftware":"0000012F","NomeLeitor":"SCR916","NumeroSerieLeitor":"5F500F53","NumLeitor":0,"BlStatusLeitor":1}],"ContadoresInternos":[0,0],"DataHora":"2022-09-15 23:30:19","NumeroSerieSLM":"8000B0CC","SLMTempoExecucao":3026,"AndroidTempoExecucao":3049} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-15 23:30:34 | WD_ERROR: EXP => 12093 | REC => 12094 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:30:41 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:30:41 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 23:31:12 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 23:31:12 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 23:31:18 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-15 23:31:35 | WD_ERROR: EXP => 12336 | REC => 12337 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:31:43 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:31:43 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 23:32:13 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 23:32:13 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 23:32:18 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-15 23:32:36 | WD_ERROR: EXP => 12579 | REC => 12580 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:32:44 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:32:44 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 23:33:14 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:33:14 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-15 23:33:19 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-15 23:33:37 | WD_ERROR: EXP => 12822 | REC => 12823 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-15 23:33:45 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-15 23:33:45 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-15 23:34:15 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

