
EXCEPTION | 2022-09-16 00:32:21 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:32:51 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:32:51 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 00:33:12 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-16 00:33:15 | WD_ERROR: EXP => 27074 | REC => 27075 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 00:33:22 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:33:22 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:33:52 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:33:52 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 00:34:13 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-16 00:34:15 | WD_ERROR: EXP => 27313 | REC => 27314 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 00:34:23 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:34:23 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:34:53 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:34:53 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 00:35:14 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-16 00:35:15 | WD_ERROR: EXP => 27552 | REC => 27553 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 00:35:22 | <<<--- | Erro ao obter hora de Servidor NTP: null[libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:551), libcore.io.IoBridge.recvfrom(IoBridge.java:509), java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:161), java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:169), java.net.DatagramSocket.receive(DatagramSocket.java:250), org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:89), br.inf.planeta.pedagio.DateTimeNTPServer.setSystemDateTimeWithDateTimeFromNTPServer(DateTimeNTPServer.java:25), br.inf.planeta.services.OneSecService$1.run(OneSecService.java:189), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422), java.util.concurrent.FutureTask.run(FutureTask.java:237), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | br.inf.planeta.services.OneSecService$1 (run line: 189) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (run line: 237)
EXCEPTION | 2022-09-16 00:35:24 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:35:24 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
REST | 2022-09-16 00:35:32 | --->>> | Response: {"VersaoSoftware":"9.6.5","Antenas":[{"VersaoSoftware":"0000012F","NomeLeitor":"SCR916","NumeroSerieLeitor":"5F500F53","NumLeitor":0,"BlStatusLeitor":1}],"ContadoresInternos":[0,0],"DataHora":"2022-09-16 00:35:32","NumeroSerieSLM":"8000B0CC","SLMTempoExecucao":6939,"AndroidTempoExecucao":6962} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 00:35:54 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:35:54 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 00:36:15 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-16 00:36:16 | WD_ERROR: EXP => 27795 | REC => 27796 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 00:36:25 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:36:25 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:36:55 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:36:55 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 00:37:16 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-16 00:37:17 | WD_ERROR: EXP => 28038 | REC => 28039 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 00:37:26 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:37:26 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:37:57 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:37:57 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 00:38:17 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-16 00:38:18 | WD_ERROR: EXP => 28281 | REC => 28282 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 00:38:27 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:38:27 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:38:58 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:38:58 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 00:39:18 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
WD_ERROR | 2022-09-16 00:39:19 | WD_ERROR: EXP => 28524 | REC => 28525 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 00:39:29 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:39:29 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
DAILY_STATS | 2022-09-16 00:39:36 | {} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

VLIB_SESSION_STATS | 2022-09-16 00:39:36 | {"vmeshVersionStr":"","vlibVersionStr":"1.2.0-global","vlibId":"","vlibGitVersion":"4749542076657273696F6E206E6F7420617661696C61626C652100000000000000000000000000000000","ulibVersionStr":"1.0.1","samCsn":"58434C0062E15DF9","samBuildTime":"23:10:19","samBuildDate":"Nov 12 2019","samAtr":"3B1D97434C5F53414D00143800009000","readerModel":"SCR916","enabledKernelApps":[0,6,6,6,0,0,0,0,0,0,0,0,0,0,0,0],"emvSamConfig":"3000010545434F39","unifiedControlRequest":0,"configControlRequest":0,"enabledKernelBits":67108878,"httpReuses":0,"lastPspData":0,"lastSlsData":1663292404,"listFlags":134217732,"onlineTimeout":-7169,"pspErrors":0,"pspServerHit":0,"pspServerStatus":0,"pspUrlIndex":0,"qrcodeTransactions":0,"readerErrors":0,"emvCancellations":0,"readerSn":1599082323,"readerVersion":303,"rfu":0,"dnsErrors":0,"diskWriteFail":0,"diskReadFail":0,"emvConfirmations":0,"samErrors":0,"samResets":1,"samTtc":0,"samVersion":14356,"sessionUnifiedAdded":0,"sessionUnifiedRemoved":0,"sessionUnifiedUpdated":0,"size":477,"slsServerHit":7172,"startTime":1663292407,"tcpConnections":1,"tcpErrors":0,"tcpRetries":0,"timestamp":1663299576,"tlsHandshakeErrors":0,"transactionSuccess":0,"bytesSent":184,"emvTransactions":0,"unifiedListItems":0,"unsyncedMismatchCount":0,"updateServerStatus":1,"virtualStatus":0,"virtualTransactions":0,"bytesReceived":69,"avrListItems":0,"vlibUptime":7169,"avrGlobalCount":0,"abtTransactions":0,"vreadyStatus":1} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 00:40:00 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:40:00 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 00:40:19 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

WD_ERROR | 2022-09-16 00:40:19 | WD_ERROR: EXP => 28763 | REC => 28764 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 00:40:23 | <<<--- | Erro ao obter hora de Servidor NTP: null[libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:551), libcore.io.IoBridge.recvfrom(IoBridge.java:509), java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:161), java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:169), java.net.DatagramSocket.receive(DatagramSocket.java:250), org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:89), br.inf.planeta.pedagio.DateTimeNTPServer.setSystemDateTimeWithDateTimeFromNTPServer(DateTimeNTPServer.java:25), br.inf.planeta.services.OneSecService$1.run(OneSecService.java:189), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422), java.util.concurrent.FutureTask.run(FutureTask.java:237), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | br.inf.planeta.services.OneSecService$1 (run line: 189) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (run line: 237)
EXCEPTION | 2022-09-16 00:40:31 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:40:31 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
REST | 2022-09-16 00:40:33 | --->>> | Response: {"VersaoSoftware":"9.6.5","Antenas":[{"VersaoSoftware":"0000012F","NomeLeitor":"SCR916","NumeroSerieLeitor":"5F500F53","NumLeitor":0,"BlStatusLeitor":1}],"ContadoresInternos":[0,0],"DataHora":"2022-09-16 00:40:33","NumeroSerieSLM":"8000B0CC","SLMTempoExecucao":7240,"AndroidTempoExecucao":7263} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 00:41:01 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:41:01 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 00:41:20 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

WD_ERROR | 2022-09-16 00:41:20 | WD_ERROR: EXP => 29006 | REC => 29007 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 00:41:32 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:41:32 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:42:03 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:42:03 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 00:42:20 | WD_ERROR: EXP => 29245 | REC => 29246 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

ETH_LOG | 2022-09-16 00:42:21 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 00:42:34 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:42:34 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:43:04 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:43:04 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 00:43:21 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

WD_ERROR | 2022-09-16 00:43:21 | WD_ERROR: EXP => 29488 | REC => 29489 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 00:43:35 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:43:35 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:44:06 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:44:06 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 00:44:22 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

WD_ERROR | 2022-09-16 00:44:22 | WD_ERROR: EXP => 29731 | REC => 29732 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 00:44:37 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:44:37 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:45:08 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:45:08 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 00:45:23 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

EXCEPTION | 2022-09-16 00:45:23 | <<<--- | Erro ao obter hora de Servidor NTP: null[libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:551), libcore.io.IoBridge.recvfrom(IoBridge.java:509), java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:161), java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:169), java.net.DatagramSocket.receive(DatagramSocket.java:250), org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:89), br.inf.planeta.pedagio.DateTimeNTPServer.setSystemDateTimeWithDateTimeFromNTPServer(DateTimeNTPServer.java:25), br.inf.planeta.services.OneSecService$1.run(OneSecService.java:189), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422), java.util.concurrent.FutureTask.run(FutureTask.java:237), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | br.inf.planeta.services.OneSecService$1 (run line: 189) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (run line: 237)

WD_ERROR | 2022-09-16 00:45:23 | WD_ERROR: EXP => 29974 | REC => 29975 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
REST | 2022-09-16 00:45:34 | --->>> | Response: {"VersaoSoftware":"9.6.5","Antenas":[{"VersaoSoftware":"0000012F","NomeLeitor":"SCR916","NumeroSerieLeitor":"5F500F53","NumLeitor":0,"BlStatusLeitor":1}],"ContadoresInternos":[0,0],"DataHora":"2022-09-16 00:45:34","NumeroSerieSLM":"8000B0CC","SLMTempoExecucao":7541,"AndroidTempoExecucao":7564} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 00:45:38 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:45:38 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:46:09 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:46:09 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 00:46:24 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

WD_ERROR | 2022-09-16 00:46:24 | WD_ERROR: EXP => 30217 | REC => 30218 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 00:46:40 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:46:40 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:47:11 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:47:11 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 00:47:25 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

WD_ERROR | 2022-09-16 00:47:25 | WD_ERROR: EXP => 30460 | REC => 30461 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 00:47:41 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:47:41 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:48:11 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:48:11 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
ETH_LOG | 2022-09-16 00:48:26 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

WD_ERROR | 2022-09-16 00:48:26 | WD_ERROR: EXP => 30703 | REC => 30704 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 00:48:42 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:48:42 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:49:13 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:49:13 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 00:49:26 | WD_ERROR: EXP => 30942 | REC => 30943 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

ETH_LOG | 2022-09-16 00:49:27 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
DAILY_STATS | 2022-09-16 00:49:37 | {} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

VLIB_SESSION_STATS | 2022-09-16 00:49:37 | {"vmeshVersionStr":"","vlibVersionStr":"1.2.0-global","vlibId":"","vlibGitVersion":"4749542076657273696F6E206E6F7420617661696C61626C652100000000000000000000000000000000","ulibVersionStr":"1.0.1","samCsn":"58434C0062E15DF9","samBuildTime":"23:10:19","samBuildDate":"Nov 12 2019","samAtr":"3B1D97434C5F53414D00143800009000","readerModel":"SCR916","enabledKernelApps":[0,6,6,6,0,0,0,0,0,0,0,0,0,0,0,0],"emvSamConfig":"3000010545434F39","unifiedControlRequest":0,"configControlRequest":0,"enabledKernelBits":67108878,"httpReuses":0,"lastPspData":0,"lastSlsData":1663292404,"listFlags":134217732,"onlineTimeout":-7770,"pspErrors":0,"pspServerHit":0,"pspServerStatus":0,"pspUrlIndex":0,"qrcodeTransactions":0,"readerErrors":0,"emvCancellations":0,"readerSn":1599082323,"readerVersion":303,"rfu":0,"dnsErrors":0,"diskWriteFail":0,"diskReadFail":0,"emvConfirmations":0,"samErrors":0,"samResets":1,"samTtc":0,"samVersion":14356,"sessionUnifiedAdded":0,"sessionUnifiedRemoved":0,"sessionUnifiedUpdated":0,"size":477,"slsServerHit":7773,"startTime":1663292407,"tcpConnections":1,"tcpErrors":0,"tcpRetries":0,"timestamp":1663300177,"tlsHandshakeErrors":0,"transactionSuccess":0,"bytesSent":184,"emvTransactions":0,"unifiedListItems":0,"unsyncedMismatchCount":0,"updateServerStatus":1,"virtualStatus":0,"virtualTransactions":0,"bytesReceived":69,"avrListItems":0,"vlibUptime":7770,"avrGlobalCount":0,"abtTransactions":0,"vreadyStatus":1} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 00:49:44 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:49:44 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:50:14 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:50:14 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:50:24 | <<<--- | Erro ao obter hora de Servidor NTP: null[libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:551), libcore.io.IoBridge.recvfrom(IoBridge.java:509), java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:161), java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:169), java.net.DatagramSocket.receive(DatagramSocket.java:250), org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:89), br.inf.planeta.pedagio.DateTimeNTPServer.setSystemDateTimeWithDateTimeFromNTPServer(DateTimeNTPServer.java:25), br.inf.planeta.services.OneSecService$1.run(OneSecService.java:189), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422), java.util.concurrent.FutureTask.run(FutureTask.java:237), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | br.inf.planeta.services.OneSecService$1 (run line: 189) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (run line: 237)
WD_ERROR | 2022-09-16 00:50:26 | WD_ERROR: EXP => 31181 | REC => 31182 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
ETH_LOG | 2022-09-16 00:50:28 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
REST | 2022-09-16 00:50:35 | --->>> | Response: {"VersaoSoftware":"9.6.5","Antenas":[{"VersaoSoftware":"0000012F","NomeLeitor":"SCR916","NumeroSerieLeitor":"5F500F53","NumLeitor":0,"BlStatusLeitor":1}],"ContadoresInternos":[0,0],"DataHora":"2022-09-16 00:50:35","NumeroSerieSLM":"8000B0CC","SLMTempoExecucao":7842,"AndroidTempoExecucao":7865} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 00:50:44 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:50:44 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:51:14 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:51:14 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 00:51:27 | WD_ERROR: EXP => 31423 | REC => 31424 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
ETH_LOG | 2022-09-16 00:51:29 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 00:51:44 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:51:44 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:52:15 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:52:15 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 00:52:27 | WD_ERROR: EXP => 31662 | REC => 31663 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
ETH_LOG | 2022-09-16 00:52:30 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 00:52:46 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:52:46 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:53:16 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:53:16 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 00:53:28 | WD_ERROR: EXP => 31905 | REC => 31906 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
ETH_LOG | 2022-09-16 00:53:31 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 00:53:47 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:53:47 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:54:17 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:54:17 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 00:54:29 | WD_ERROR: EXP => 32148 | REC => 32149 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
ETH_LOG | 2022-09-16 00:54:32 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 00:54:48 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:54:48 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:55:18 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:55:18 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:55:24 | <<<--- | Erro ao obter hora de Servidor NTP: null[libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:551), libcore.io.IoBridge.recvfrom(IoBridge.java:509), java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:161), java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:169), java.net.DatagramSocket.receive(DatagramSocket.java:250), org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:89), br.inf.planeta.pedagio.DateTimeNTPServer.setSystemDateTimeWithDateTimeFromNTPServer(DateTimeNTPServer.java:25), br.inf.planeta.services.OneSecService$1.run(OneSecService.java:189), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422), java.util.concurrent.FutureTask.run(FutureTask.java:237), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | br.inf.planeta.services.OneSecService$1 (run line: 189) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (run line: 237)
WD_ERROR | 2022-09-16 00:55:30 | WD_ERROR: EXP => 32391 | REC => 32392 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
ETH_LOG | 2022-09-16 00:55:33 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
REST | 2022-09-16 00:55:36 | --->>> | Response: {"VersaoSoftware":"9.6.5","Antenas":[{"VersaoSoftware":"0000012F","NomeLeitor":"SCR916","NumeroSerieLeitor":"5F500F53","NumLeitor":0,"BlStatusLeitor":1}],"ContadoresInternos":[0,0],"DataHora":"2022-09-16 00:55:36","NumeroSerieSLM":"8000B0CC","SLMTempoExecucao":8143,"AndroidTempoExecucao":8166} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 00:55:49 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:55:49 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:56:20 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:56:20 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 00:56:30 | WD_ERROR: EXP => 32630 | REC => 32631 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
ETH_LOG | 2022-09-16 00:56:34 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 00:56:51 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:56:51 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:57:22 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:57:22 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 00:57:31 | WD_ERROR: EXP => 32873 | REC => 32874 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
ETH_LOG | 2022-09-16 00:57:35 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 00:57:52 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:57:52 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:58:23 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:58:23 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 00:58:31 | WD_ERROR: EXP => 33112 | REC => 33113 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
ETH_LOG | 2022-09-16 00:58:36 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 00:58:53 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:58:53 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:59:24 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 00:59:24 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 00:59:32 | WD_ERROR: EXP => 33355 | REC => 33356 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
ETH_LOG | 2022-09-16 00:59:37 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
DAILY_STATS | 2022-09-16 00:59:38 | {} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

VLIB_SESSION_STATS | 2022-09-16 00:59:38 | {"vmeshVersionStr":"","vlibVersionStr":"1.2.0-global","vlibId":"","vlibGitVersion":"4749542076657273696F6E206E6F7420617661696C61626C652100000000000000000000000000000000","ulibVersionStr":"1.0.1","samCsn":"58434C0062E15DF9","samBuildTime":"23:10:19","samBuildDate":"Nov 12 2019","samAtr":"3B1D97434C5F53414D00143800009000","readerModel":"SCR916","enabledKernelApps":[0,6,6,6,0,0,0,0,0,0,0,0,0,0,0,0],"emvSamConfig":"3000010545434F39","unifiedControlRequest":0,"configControlRequest":0,"enabledKernelBits":67108878,"httpReuses":0,"lastPspData":0,"lastSlsData":1663292404,"listFlags":134217732,"onlineTimeout":-8371,"pspErrors":0,"pspServerHit":0,"pspServerStatus":0,"pspUrlIndex":0,"qrcodeTransactions":0,"readerErrors":0,"emvCancellations":0,"readerSn":1599082323,"readerVersion":303,"rfu":0,"dnsErrors":0,"diskWriteFail":0,"diskReadFail":0,"emvConfirmations":0,"samErrors":0,"samResets":1,"samTtc":0,"samVersion":14356,"sessionUnifiedAdded":0,"sessionUnifiedRemoved":0,"sessionUnifiedUpdated":0,"size":477,"slsServerHit":8374,"startTime":1663292407,"tcpConnections":1,"tcpErrors":0,"tcpRetries":0,"timestamp":1663300778,"tlsHandshakeErrors":0,"transactionSuccess":0,"bytesSent":184,"emvTransactions":0,"unifiedListItems":0,"unsyncedMismatchCount":0,"updateServerStatus":1,"virtualStatus":0,"virtualTransactions":0,"bytesReceived":69,"avrListItems":0,"vlibUptime":8371,"avrGlobalCount":0,"abtTransactions":0,"vreadyStatus":1} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 00:59:55 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 00:59:55 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 01:00:25 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 01:00:25 | <<<--- | Erro ao obter hora de Servidor NTP: null[libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:551), libcore.io.IoBridge.recvfrom(IoBridge.java:509), java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:161), java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:169), java.net.DatagramSocket.receive(DatagramSocket.java:250), org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:89), br.inf.planeta.pedagio.DateTimeNTPServer.setSystemDateTimeWithDateTimeFromNTPServer(DateTimeNTPServer.java:25), br.inf.planeta.services.OneSecService$1.run(OneSecService.java:189), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422), java.util.concurrent.FutureTask.run(FutureTask.java:237), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | br.inf.planeta.services.OneSecService$1 (run line: 189) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (run line: 237)

EXCEPTION | 2022-09-16 01:00:25 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 01:00:33 | WD_ERROR: EXP => 33598 | REC => 33599 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
REST | 2022-09-16 01:00:37 | --->>> | Response: {"VersaoSoftware":"9.6.5","Antenas":[{"VersaoSoftware":"0000012F","NomeLeitor":"SCR916","NumeroSerieLeitor":"5F500F53","NumLeitor":0,"BlStatusLeitor":1}],"ContadoresInternos":[0,0],"DataHora":"2022-09-16 01:00:37","NumeroSerieSLM":"8000B0CC","SLMTempoExecucao":8444,"AndroidTempoExecucao":8467} | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)

ETH_LOG | 2022-09-16 01:00:37 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 01:00:56 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 01:00:56 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
EXCEPTION | 2022-09-16 01:01:27 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

EXCEPTION | 2022-09-16 01:01:27 | bind failed: EADDRINUSE (Address already in use) | [libcore.io.IoBridge.bind(IoBridge.java:89), java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150), java.net.ServerSocket.bind(ServerSocket.java:319), java.net.ServerSocket.bind(ServerSocket.java:282), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:65), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 
WD_ERROR | 2022-09-16 01:01:34 | WD_ERROR: EXP => 33841 | REC => 33842 | br.inf.planeta.pedagio.Manager$1 (run line: 822) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
ETH_LOG | 2022-09-16 01:01:38 | Eth OK | br.inf.planeta.services.OneSecService$4 (run line: 685) -> java.util.concurrent.Executors$RunnableAdapter (call line: 422) -> java.util.concurrent.FutureTask (runAndReset line: 279)
EXCEPTION | 2022-09-16 01:01:57 | Socket closed | [libcore.io.Posix.accept(Native Method), libcore.io.BlockGuardOs.accept(BlockGuardOs.java:55), java.net.PlainSocketImpl.accept(PlainSocketImpl.java:98), java.net.ServerSocket.implAccept(ServerSocket.java:203), java.net.ServerSocket.accept(ServerSocket.java:128), org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:76), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:841)] | java.util.concurrent.ThreadPoolExecutor (runWorker line: 1112) -> java.util.concurrent.ThreadPoolExecutor$Worker (run line: 587) -> 

